source 'https://rubygems.org'

# Ruby version
ruby '2.1.1'

# Default gems
gem 'rails', '4.1.0'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'

# Rails doc
group :doc do
  # Run bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', '~> 0.4.0', require: false
end

# Development gems
group :development do
  gem 'sqlite3', '~> 1.3.9'
  gem 'spring'
  gem 'better_errors'
  gem 'binding_of_caller'
end

# Production gems
group :production do
  gem 'rails_12factor'
  gem 'pg'
end
